services:
  zabbix-frontend:
    image: alpinelinux/zabbix-ci:7.0
    ports:
     - 7871:8080
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      DB_SERVER_HOST: db
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Etc/UTC
    depends_on:
      - db
    healthcheck:
      test: [
        CMD, curl, -s, --fail, http://localhost:8080/api_jsonrpc.php,
        --json, '{"id": "1", "jsonrpc": "2.0", "method": "apiinfo.version", "params": {}}'
        ]
      interval: 3s
      timeout: 1s
      retries: 10
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix

  integration-test:
    image: php:8.1-cli-alpine
    profiles: [command]
    command: vendor/bin/phpunit integration/
    volumes:
      - ./:/src
    working_dir: /src

  test:
    image: php:8.1-cli-alpine
    profiles: [command]
    command: vendor/bin/phpunit test/
    volumes:
      - ./:/src
    working_dir: /src
